version: "3"
networks: 
  main: 
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.25.255.0/24
      driver: default
services:
  pub:
    build: .
    ports:
     - "5001:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
    networks: 
      main: 
        ipv4_address: "172.25.255.9" 
  redis:
    image: redis
    ports:
     - "6381:6379"
    expose:
     - 6380 
    networks: 
      main: 
        ipv4_address: "172.25.255.8" 
  nats-1: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://172.25.255.10:6222"
    expose:
      - "6222"
    image: "nats"
    networks: 
      main: 
        ipv4_address: "172.25.255.10"
    ports:
      - "14222:4222"
  nats-2: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://172.25.255.20:6222"
      - "-routes"
      - "nats://172.25.255.10:6222"
    image: "nats"
    expose:
      - "6222"
    networks: 
      main: 
        ipv4_address: "172.25.255.20"
    ports:
      - "24222:4222"
  nats-3: 
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://172.25.255.30:6222"
      - "-routes"
      - "nats://172.25.255.10:6222"
    image: "nats"
    expose:
      - "6222"
    networks: 
      main: 
        ipv4_address: "172.25.255.30"
    ports:
      - "34222:4222"
