version: '3'
services:
  nats:
    image: 'nats'
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:6222"
      - "-routes"
      - "nats://192.168.1.34:6222"
    expose:
      - "4222"
      - "8222"
      - "6222"
    ports:
      - "8222:8222"
      - "4222:4222"
