version: '3'
services:
  pub:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  redis:
    image: redis
    ports:
     - "6380:6379"
    expose:
     - 6380
  nats:
    image: 'nats'
    command: 
      - "-D"
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:6222"
    expose:
      - "4222"
      - "8222"
      - "6222"
    ports:
      - "8222:8222"
      - "4222:4222"
